# Generated by Django 4.2.1 on 2023-05-26 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number is not correct', regex='\\A(09)(0|1|2|3)[0-9]{7}\\d\\Z')]),
        ),
    ]
